In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('autos.csv')
df

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [3]:
df.isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

In [6]:
df['dateCrawled'] = pd.to_datetime(df['dateCrawled'], errors='coerce')
df['dateCreated'] = pd.to_datetime(df['dateCreated'], errors='coerce')
df['lastSeen'] = pd.to_datetime(df['lastSeen'], errors='coerce')

df['dateCrawled'] = df['dateCrawled'].dt.date
df['dateCreated'] = df['dateCreated'].dt.date
df['lastSeen'] = df['lastSeen'].dt.date

df

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24,0,70435,2016-04-07
1,1,2016-03-24,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24,0,66954,2016-04-07
2,2,2016-03-14,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14,0,90480,2016-04-05
3,3,2016-03-17,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17,0,91074,2016-03-17
4,4,2016-03-31,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31,0,60437,2016-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14,0,39576,2016-04-06
371524,371524,2016-03-05,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05,0,26135,2016-03-11
371525,371525,2016-03-19,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19,0,87439,2016-04-07
371526,371526,2016-03-20,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20,0,40764,2016-03-24
371527,371527,2016-03-07,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07,0,73326,2016-03-22

In [7]:
df ['name'] = df['name'].replace('_', ' ', regex=True)
df

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24,Golf 3 1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24,0,70435,2016-04-07
1,1,2016-03-24,A5 Sportback 2.7 Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24,0,66954,2016-04-07
2,2,2016-03-14,"Jeep Grand Cherokee ""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14,0,90480,2016-04-05
3,3,2016-03-17,GOLF 4 1 4 3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17,0,91074,2016-03-17
4,4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31,0,60437,2016-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14,Suche t4 vito ab 6 sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14,0,39576,2016-04-06
371524,371524,2016-03-05,Smart smart leistungssteigerung 100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05,0,26135,2016-03-11
371525,371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19,0,87439,2016-04-07
371526,371526,2016-03-20,VW Golf Kombi 1 9l TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20,0,40764,2016-03-24
371527,371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07,0,73326,2016-03-22

In [8]:
df = df[df['yearOfRegistration'] > 1900]
df

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24,Golf 3 1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24,0,70435,2016-04-07
1,1,2016-03-24,A5 Sportback 2.7 Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24,0,66954,2016-04-07
2,2,2016-03-14,"Jeep Grand Cherokee ""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14,0,90480,2016-04-05
3,3,2016-03-17,GOLF 4 1 4 3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17,0,91074,2016-03-17
4,4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31,0,60437,2016-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14,Suche t4 vito ab 6 sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14,0,39576,2016-04-06
371524,371524,2016-03-05,Smart smart leistungssteigerung 100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05,0,26135,2016-03-11
371525,371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19,0,87439,2016-04-07
371526,371526,2016-03-20,VW Golf Kombi 1 9l TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20,0,40764,2016-03-24
371527,371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07,0,73326,2016-03-22

In [9]:
df = df.drop(['postalCode', 'nrOfPictures', 'index'], axis=1)

In [10]:
df['notRepairedDamage'] = df['notRepairedDamage'].replace('nein', 'no')
df['notRepairedDamage'] = df['notRepairedDamage'].replace('ja', 'yes')

df['offerType'] = df['offerType'].replace('angebot', 'offer')
df['offerType'] = df['offerType'].replace('gesuch', 'request')
df['vehicleType'] = df['vehicleType'].replace('kleinwagen', 'hatchback')
df['vehicleType'] = df['vehicleType'].replace('limousine', 'sedan')
df['vehicleType'] = df['vehicleType'].replace('kombi', 'station wagon')
df['vehicleType'] = df['vehicleType'].replace('andere', 'other')

df['seller'] = df['seller'].replace('privat', 'private')
df['seller'] = df['seller'].replace('gewerblich', 'commercial')
df['seller'] = df['seller'].replace('Angebot', 'offer')

df['fuelType'] = df['fuelType'].replace('benzin', 'gasoline')
df['fuelType'] = df['fuelType'].replace('elektro', 'electric')
df['fuelType'] = df['fuelType'].replace('andere', 'other')

df['gearbox'] = df['gearbox'].replace('manuell', 'manual')
df['gearbox'] = df['gearbox'].replace('automatik', 'automatic')

df

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen
0,2016-03-24,Golf 3 1.6,private,Angebot,480,test,NaN,1993,manual,0,golf,150000,0,gasoline,volkswagen,NaN,2016-03-24,2016-04-07
1,2016-03-24,A5 Sportback 2.7 Tdi,private,Angebot,18300,test,coupe,2011,manual,190,NaN,125000,5,diesel,audi,yes,2016-03-24,2016-04-07
2,2016-03-14,"Jeep Grand Cherokee ""Overland""",private,Angebot,9800,test,suv,2004,automatic,163,grand,125000,8,diesel,jeep,NaN,2016-03-14,2016-04-05
3,2016-03-17,GOLF 4 1 4 3TÜRER,private,Angebot,1500,test,hatchback,2001,manual,75,golf,150000,6,gasoline,volkswagen,no,2016-03-17,2016-03-17
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,private,Angebot,3600,test,hatchback,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31,2016-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2016-03-14,Suche t4 vito ab 6 sitze,private,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14,2016-04-06
371524,2016-03-05,Smart smart leistungssteigerung 100ps,private,Angebot,1199,test,cabrio,2000,automatic,101,fortwo,125000,3,gasoline,smart,no,2016-03-05,2016-03-11
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,private,Angebot,9200,test,bus,1996,manual,102,transporter,150000,3,diesel,volkswagen,no,2016-03-19,2016-04-07
371526,2016-03-20,VW Golf Kombi 1 9l TDI,private,Angebot,3400,test,station wagon,2002,manual,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20,2016-03-24
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,private,Angebot,28990,control,sedan,2013,manual,320,m_reihe,50000,8,gasoline,bmw,no,2016-03-07,2016-03-22

In [11]:
df = df.dropna(subset=['notRepairedDamage', 'vehicleType', 'powerPS', 'fuelType', 'model', 'gearbox'])
df

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen
3,2016-03-17,GOLF 4 1 4 3TÜRER,private,Angebot,1500,test,hatchback,2001,manual,75,golf,150000,6,gasoline,volkswagen,no,2016-03-17,2016-03-17
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,private,Angebot,3600,test,hatchback,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31,2016-04-06
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,private,Angebot,650,test,sedan,1995,manual,102,3er,150000,10,gasoline,bmw,yes,2016-04-04,2016-04-06
6,2016-04-01,Peugeot 206 CC 110 Platinum,private,Angebot,2200,test,cabrio,2004,manual,109,2_reihe,150000,8,gasoline,peugeot,no,2016-04-01,2016-04-05
7,2016-03-21,VW Derby Bj 80 Scheunenfund,private,Angebot,0,test,sedan,1980,manual,50,andere,40000,7,gasoline,volkswagen,no,2016-03-21,2016-03-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,private,Angebot,3200,control,sedan,2004,manual,225,leon,150000,5,gasoline,seat,yes,2016-03-19,2016-03-19
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,private,Angebot,1150,control,bus,2000,manual,0,zafira,150000,3,gasoline,opel,no,2016-03-27,2016-03-29
371524,2016-03-05,Smart smart leistungssteigerung 100ps,private,Angebot,1199,test,cabrio,2000,automatic,101,fortwo,125000,3,gasoline,smart,no,2016-03-05,2016-03-11
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,private,Angebot,9200,test,bus,1996,manual,102,transporter,150000,3,diesel,volkswagen,no,2016-03-19,2016-04-07
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,private,Angebot,28990,control,sedan,2013,manual,320,m_reihe,50000,8,gasoline,bmw,no,2016-03-07,2016-03-22

In [12]:
valid_fuels = ['gasoline', 'diesel', 'lpg', 'electric', 'other','cng']
df = df[df['fuelType'].isin(valid_fuels)]
valid_gearboxes = ['manual', 'automatic']
df = df[df['gearbox'].isin(valid_gearboxes)]
non_valid_brands = ['ja','nein']
df = df[~df['brand'].isin(non_valid_brands)]
no_valid_vechile_types = ['other']
df = df[~df['vehicleType'].isin(no_valid_vechile_types)]

In [13]:
df = df[df['offerType'] != 'request']
df
df.drop('offerType', axis=1, inplace=True)
df

,dateCrawled,name,seller,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen
3,2016-03-17,GOLF 4 1 4 3TÜRER,private,1500,test,hatchback,2001,manual,75,golf,150000,6,gasoline,volkswagen,no,2016-03-17,2016-03-17
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,private,3600,test,hatchback,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31,2016-04-06
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,private,650,test,sedan,1995,manual,102,3er,150000,10,gasoline,bmw,yes,2016-04-04,2016-04-06
6,2016-04-01,Peugeot 206 CC 110 Platinum,private,2200,test,cabrio,2004,manual,109,2_reihe,150000,8,gasoline,peugeot,no,2016-04-01,2016-04-05
7,2016-03-21,VW Derby Bj 80 Scheunenfund,private,0,test,sedan,1980,manual,50,andere,40000,7,gasoline,volkswagen,no,2016-03-21,2016-03-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,private,3200,control,sedan,2004,manual,225,leon,150000,5,gasoline,seat,yes,2016-03-19,2016-03-19
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,private,1150,control,bus,2000,manual,0,zafira,150000,3,gasoline,opel,no,2016-03-27,2016-03-29
371524,2016-03-05,Smart smart leistungssteigerung 100ps,private,1199,test,cabrio,2000,automatic,101,fortwo,125000,3,gasoline,smart,no,2016-03-05,2016-03-11
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,private,9200,test,bus,1996,manual,102,transporter,150000,3,diesel,volkswagen,no,2016-03-19,2016-04-07
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,private,28990,control,sedan,2013,manual,320,m_reihe,50000,8,gasoline,bmw,no,2016-03-07,2016-03-22

In [14]:
df = df.drop(columns=['seller'])

In [15]:
df

,dateCrawled,name,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen
3,2016-03-17,GOLF 4 1 4 3TÜRER,1500,test,hatchback,2001,manual,75,golf,150000,6,gasoline,volkswagen,no,2016-03-17,2016-03-17
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,3600,test,hatchback,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31,2016-04-06
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,650,test,sedan,1995,manual,102,3er,150000,10,gasoline,bmw,yes,2016-04-04,2016-04-06
6,2016-04-01,Peugeot 206 CC 110 Platinum,2200,test,cabrio,2004,manual,109,2_reihe,150000,8,gasoline,peugeot,no,2016-04-01,2016-04-05
7,2016-03-21,VW Derby Bj 80 Scheunenfund,0,test,sedan,1980,manual,50,andere,40000,7,gasoline,volkswagen,no,2016-03-21,2016-03-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,3200,control,sedan,2004,manual,225,leon,150000,5,gasoline,seat,yes,2016-03-19,2016-03-19
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,1150,control,bus,2000,manual,0,zafira,150000,3,gasoline,opel,no,2016-03-27,2016-03-29
371524,2016-03-05,Smart smart leistungssteigerung 100ps,1199,test,cabrio,2000,automatic,101,fortwo,125000,3,gasoline,smart,no,2016-03-05,2016-03-11
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,9200,test,bus,1996,manual,102,transporter,150000,3,diesel,volkswagen,no,2016-03-19,2016-04-07
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,28990,control,sedan,2013,manual,320,m_reihe,50000,8,gasoline,bmw,no,2016-03-07,2016-03-22

In [16]:
df['car_age'] = 2016 - df['yearOfRegistration']
df

,dateCrawled,name,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen,car_age
3,2016-03-17,GOLF 4 1 4 3TÜRER,1500,test,hatchback,2001,manual,75,golf,150000,6,gasoline,volkswagen,no,2016-03-17,2016-03-17,15
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,3600,test,hatchback,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31,2016-04-06,8
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,650,test,sedan,1995,manual,102,3er,150000,10,gasoline,bmw,yes,2016-04-04,2016-04-06,21
6,2016-04-01,Peugeot 206 CC 110 Platinum,2200,test,cabrio,2004,manual,109,2_reihe,150000,8,gasoline,peugeot,no,2016-04-01,2016-04-05,12
7,2016-03-21,VW Derby Bj 80 Scheunenfund,0,test,sedan,1980,manual,50,andere,40000,7,gasoline,volkswagen,no,2016-03-21,2016-03-25,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,3200,control,sedan,2004,manual,225,leon,150000,5,gasoline,seat,yes,2016-03-19,2016-03-19,12
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,1150,control,bus,2000,manual,0,zafira,150000,3,gasoline,opel,no,2016-03-27,2016-03-29,16
371524,2016-03-05,Smart smart leistungssteigerung 100ps,1199,test,cabrio,2000,automatic,101,fortwo,125000,3,gasoline,smart,no,2016-03-05,2016-03-11,16
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,9200,test,bus,1996,manual,102,transporter,150000,3,diesel,volkswagen,no,2016-03-19,2016-04-07,20
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,28990,control,sedan,2013,manual,320,m_reihe,50000,8,gasoline,bmw,no,2016-03-07,2016-03-22,3

In [17]:
df.loc[df['car_age'] == 0, 'car_age'] = 1

In [18]:
df['price_in_thousands'] = df['price'] / 1000
df.drop('price', axis=1, inplace=True)
df

,dateCrawled,name,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen,car_age,price_in_thousands
3,2016-03-17,GOLF 4 1 4 3TÜRER,test,hatchback,2001,manual,75,golf,150000,6,gasoline,volkswagen,no,2016-03-17,2016-03-17,15,1.500
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,test,hatchback,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31,2016-04-06,8,3.600
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,test,sedan,1995,manual,102,3er,150000,10,gasoline,bmw,yes,2016-04-04,2016-04-06,21,0.650
6,2016-04-01,Peugeot 206 CC 110 Platinum,test,cabrio,2004,manual,109,2_reihe,150000,8,gasoline,peugeot,no,2016-04-01,2016-04-05,12,2.200
7,2016-03-21,VW Derby Bj 80 Scheunenfund,test,sedan,1980,manual,50,andere,40000,7,gasoline,volkswagen,no,2016-03-21,2016-03-25,36,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,control,sedan,2004,manual,225,leon,150000,5,gasoline,seat,yes,2016-03-19,2016-03-19,12,3.200
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,control,bus,2000,manual,0,zafira,150000,3,gasoline,opel,no,2016-03-27,2016-03-29,16,1.150
371524,2016-03-05,Smart smart leistungssteigerung 100ps,test,cabrio,2000,automatic,101,fortwo,125000,3,gasoline,smart,no,2016-03-05,2016-03-11,16,1.199
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,test,bus,1996,manual,102,transporter,150000,3,diesel,volkswagen,no,2016-03-19,2016-04-07,20,9.200
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,control,sedan,2013,manual,320,m_reihe,50000,8,gasoline,bmw,no,2016-03-07,2016-03-22,3,28.990

In [19]:
df['kilometer']  = df['kilometer'] / 1000
df['powerPS']  = df['powerPS'].astype(float)
df['car_age']  = df['car_age'].astype(float)
df

,dateCrawled,name,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen,car_age,price_in_thousands
3,2016-03-17,GOLF 4 1 4 3TÜRER,test,hatchback,2001,manual,75.0,golf,150.0,6,gasoline,volkswagen,no,2016-03-17,2016-03-17,15.0,1.500
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,test,hatchback,2008,manual,69.0,fabia,90.0,7,diesel,skoda,no,2016-03-31,2016-04-06,8.0,3.600
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,test,sedan,1995,manual,102.0,3er,150.0,10,gasoline,bmw,yes,2016-04-04,2016-04-06,21.0,0.650
6,2016-04-01,Peugeot 206 CC 110 Platinum,test,cabrio,2004,manual,109.0,2_reihe,150.0,8,gasoline,peugeot,no,2016-04-01,2016-04-05,12.0,2.200
7,2016-03-21,VW Derby Bj 80 Scheunenfund,test,sedan,1980,manual,50.0,andere,40.0,7,gasoline,volkswagen,no,2016-03-21,2016-03-25,36.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,control,sedan,2004,manual,225.0,leon,150.0,5,gasoline,seat,yes,2016-03-19,2016-03-19,12.0,3.200
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,control,bus,2000,manual,0.0,zafira,150.0,3,gasoline,opel,no,2016-03-27,2016-03-29,16.0,1.150
371524,2016-03-05,Smart smart leistungssteigerung 100ps,test,cabrio,2000,automatic,101.0,fortwo,125.0,3,gasoline,smart,no,2016-03-05,2016-03-11,16.0,1.199
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,test,bus,1996,manual,102.0,transporter,150.0,3,diesel,volkswagen,no,2016-03-19,2016-04-07,20.0,9.200
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,control,sedan,2013,manual,320.0,m_reihe,50.0,8,gasoline,bmw,no,2016-03-07,2016-03-22,3.0,28.990

In [20]:
df['price_in_thousands'] = df['price_in_thousands'].fillna(df.groupby('brand')['price_in_thousands'].transform('mean'))
df

,dateCrawled,name,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen,car_age,price_in_thousands
3,2016-03-17,GOLF 4 1 4 3TÜRER,test,hatchback,2001,manual,75.0,golf,150.0,6,gasoline,volkswagen,no,2016-03-17,2016-03-17,15.0,1.500
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,test,hatchback,2008,manual,69.0,fabia,90.0,7,diesel,skoda,no,2016-03-31,2016-04-06,8.0,3.600
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,test,sedan,1995,manual,102.0,3er,150.0,10,gasoline,bmw,yes,2016-04-04,2016-04-06,21.0,0.650
6,2016-04-01,Peugeot 206 CC 110 Platinum,test,cabrio,2004,manual,109.0,2_reihe,150.0,8,gasoline,peugeot,no,2016-04-01,2016-04-05,12.0,2.200
7,2016-03-21,VW Derby Bj 80 Scheunenfund,test,sedan,1980,manual,50.0,andere,40.0,7,gasoline,volkswagen,no,2016-03-21,2016-03-25,36.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,control,sedan,2004,manual,225.0,leon,150.0,5,gasoline,seat,yes,2016-03-19,2016-03-19,12.0,3.200
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,control,bus,2000,manual,0.0,zafira,150.0,3,gasoline,opel,no,2016-03-27,2016-03-29,16.0,1.150
371524,2016-03-05,Smart smart leistungssteigerung 100ps,test,cabrio,2000,automatic,101.0,fortwo,125.0,3,gasoline,smart,no,2016-03-05,2016-03-11,16.0,1.199
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,test,bus,1996,manual,102.0,transporter,150.0,3,diesel,volkswagen,no,2016-03-19,2016-04-07,20.0,9.200
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,control,sedan,2013,manual,320.0,m_reihe,50.0,8,gasoline,bmw,no,2016-03-07,2016-03-22,3.0,28.990

In [21]:
df.isnull().sum()

dateCrawled            0
name                   0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
lastSeen               0
car_age                0
price_in_thousands     0
dtype: int64

In [22]:
df.loc[df['price_in_thousands'] == 0 , 'price_in_thousands'] = df.groupby('brand')['price_in_thousands'].transform('mean')
df

,dateCrawled,name,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,lastSeen,car_age,price_in_thousands
3,2016-03-17,GOLF 4 1 4 3TÜRER,test,hatchback,2001,manual,75.0,golf,150.0,6,gasoline,volkswagen,no,2016-03-17,2016-03-17,15.0,1.500000
4,2016-03-31,Skoda Fabia 1.4 TDI PD Classic,test,hatchback,2008,manual,69.0,fabia,90.0,7,diesel,skoda,no,2016-03-31,2016-04-06,8.0,3.600000
5,2016-04-04,BMW 316i e36 Limousine Bastlerfahrzeug Ex...,test,sedan,1995,manual,102.0,3er,150.0,10,gasoline,bmw,yes,2016-04-04,2016-04-06,21.0,0.650000
6,2016-04-01,Peugeot 206 CC 110 Platinum,test,cabrio,2004,manual,109.0,2_reihe,150.0,8,gasoline,peugeot,no,2016-04-01,2016-04-05,12.0,2.200000
7,2016-03-21,VW Derby Bj 80 Scheunenfund,test,sedan,1980,manual,50.0,andere,40.0,7,gasoline,volkswagen,no,2016-03-21,2016-03-25,36.0,6.219247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371520,2016-03-19,turbo defekt,control,sedan,2004,manual,225.0,leon,150.0,5,gasoline,seat,yes,2016-03-19,2016-03-19,12.0,3.200000
371521,2016-03-27,Opel Zafira 1.6 Elegance TÜV 12/16,control,bus,2000,manual,0.0,zafira,150.0,3,gasoline,opel,no,2016-03-27,2016-03-29,16.0,1.150000
371524,2016-03-05,Smart smart leistungssteigerung 100ps,test,cabrio,2000,automatic,101.0,fortwo,125.0,3,gasoline,smart,no,2016-03-05,2016-03-11,16.0,1.199000
371525,2016-03-19,Volkswagen Multivan T4 TDI 7DC UY2,test,bus,1996,manual,102.0,transporter,150.0,3,diesel,volkswagen,no,2016-03-19,2016-04-07,20.0,9.200000
371527,2016-03-07,BMW M135i vollausgestattet NP 52.720 Euro,control,sedan,2013,manual,320.0,m_reihe,50.0,8,gasoline,bmw,no,2016-03-07,2016-03-22,3.0,28.990000

In [23]:
df.to_csv('cleaned_autos.csv', index=False)